#!/bin/bash
#Author:sarath
#Date:####
#
#Version:v1
#
#This script will report the aws resource usage
############################
set -x

#Aws s3
#AWs Ec2
#Aws Lambda
#AWS IAM users
#List s3 buckets
#

# List of s3 buckets
echo "print list of s3 buckets"

aws s3 ls

# list of instances
echo "Print list of aws instances"
aws ec2 describe-instances

#aws ec2 describe-instances | jq '.Reservations[].Instances[].InstancesId'
aws ec2 describe-instances | jq '.Reservations[].Instances[].InstanceId'


# List of LAMDA
echo "print list of lamda"
aws lambda list-functions

#List of IAM users
echo "print list of IAM users"
aws iam list-users
